### ISSUE TITLE
Версия 2.0

### ISSUE THREAD

**Issue by NamYoSeb** [artbutko/SummerPractice.TopologicalSort#14]
Завтра начну переписывать код полностью под наши структуры(нормализировать) с Дмитрием, если он успеет.
После переписывания, займусь визуализацией алгоритма.

Артем, после займись рефакторингом кода, все равно я проснусь раньше вас.

Дима, красавчик.

**Comment by sidtheslooth20** [comment]
Спасибо

**Comment by artbutko** [comment]
Проблемы с добавлением (удалением) ребер.

**Comment by NamYoSeb** [comment]
Сделали все, осталось поработать над оформлением, работаю с документацией

**Comment by NataRazmochaeva** [comment]
@artbutko @sidtheslooth20 @NamYoSeb 
настройте в Projects слева в меню
