### ISSUE TITLE
Final version

### ISSUE THREAD

**Issue by NamYoSeb** [artbutko/SummerPractice.TopologicalSort#22]
1.4.1.       Добавление диалоговых окон с сообщениями
1.4.2.	Добавление функций во вкладке «Помощь»
1.4.3.	Обработка ошибки «Цикл»
1.4.4.	Добавление плеера
1.4.5.	Исправление багов и недочетов в отчете

**Comment by NamYoSeb** [comment]
1.4.6. Добавить описание тестирования

**Comment by NataRazmochaeva** [comment]
@artbutko @sidtheslooth20 @NamYoSeb
настройте в Projects слева в меню
